config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'
  get 'contacter', to: "pages#contacter"
  get 'contact.vcf', to: 'pages#contact', as: 'add_contact'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :clients
  has_many :bills

  validates :email, presence: true, uniqueness: true, inclusion: { in: ['contact@kevintchiadeu.com'], message: "L'email n'est pas valide" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :client
  belongs_to :admin
  has_many :items, dependent: :destroy

  accepts_nested_attributes_for :client
  accepts_nested_attributes_for :items
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :bills
  belongs_to :admin

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  UNITY = %w[heures jours].freeze

  belongs_to :bill

  validates :unity, presence: true, inclusion: { in: UNITY }
  validates :quantity, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @bill = Bill.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "F-#{@bill.year}-#{@bill.number}",
               template: 'bills/show',
               formats: [:html],
               encoding: 'utf8'
      end
    end
  end

  def new
    @bill = Bill.new
    @bill.build_client
    @bill.items.build
  end

  def create
    @bill = Bill.new(bill_params)
    @bill.admin = current_admin
    @bill.month = Date.today.month
    @bill.year = Date.today.year
    if Bill.where(year: @bill.year) < 10
      @bill.number = "0#{Bill.where(year: @bill.year).count + 1}"
    else
      @bill.number = (Bill.where(year: @bill.year).count + 1).to_s
    end
    @bill.emission_date = Date.today
    @bill.due_date = Date.today + 30

    items = []
    10.times do |i|
      item_params = params[:bill][:item][i.to_s]
      item = Item.new(
        name: item_params[:name],
        description: item_params[:description],
        unity: item_params[:unity],
        quantity: item_params[:quantity],
        unit_price: item_params[:unit_price]
      )
      item.total_price = item.quantity.to_f * item.unit_price.to_f
      items << item if item.name.present?
    end
    @bill.items = items

    # item_params = params[:bill][:items_attributes]
    # if item_params.present?
    #   item_params.each do |item_param|
    #     item_param[:total_price] = item_param[:quantity].to_f * item_param[:unit_price].to_f
    #     @bill.items.build!(item_param)
    #   end
    # end

    client = Client.new(
      name: params[:bill][:client_attributes][:name],
      address: params[:bill][:client_attributes][:address],
      post_code: params[:bill][:client_attributes][:post_code],
      city: params[:bill][:client_attributes][:city],
      siret_number: params[:bill][:client_attributes][:siret_number],
      tva_number: params[:bill][:client_attributes][:tva_number],
      email: params[:bill][:client_attributes][:email],
      phone_number: params[:bill][:client_attributes][:phone_number]
    )
    client.admin = current_admin
    client.save
    @bill.client = client

    if @bill.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def edit
  #   @bill = Bill.find(params[:id])
  # end

  # def update
  #   @bill = Bill.find(params[:id])
  #   @bill.update(bill_params)
  # end

  # def destroy
  #   @bill = Bill.find(params[:id])
  #   @bill.destroy
  # end

  private

  def bill_params
    params.require(:bill).permit(
      :number, :payed, :total_amount, :year, :emission_date, :due_date, :month,
      client_attributes: %i[name address post_code city siret_number tva_number email phone_number],
      items_attributes: %i[name description unity quantity unit_price total_price]
    )
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    @client.save
    redirect_to @client
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    @client.update(client_params)
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
  end

  private

  def client_params
    params.require(:client).permit(
      :name, :phone_number, :email, :address, :post_code, :city, :siret_number, :tva_number
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @age = ((Date.today - Date.new(1992, 5, 6)).to_i / 365.25).to_i
  end

  def contacter
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bills/new.html.erb
<div data-controller="items">
  <%= form_with model: @bill do |form| %>

    <%= form.fields_for :client do |client_fields| %>

      <%= client_fields.label :name, "Nom" %>
      <%= client_fields.text_field :name %>

      <%= client_fields.label :address, "Addresse" %>
      <%= client_fields.text_field :address %>

      <%= client_fields.label :post_code, "Code postal" %>
      <%= client_fields.text_field :post_code %>

      <%= client_fields.label :city, "Ville" %>
      <%= client_fields.text_field :city %>

      <%= client_fields.label :siret_number, "SIRET" %>
      <%= client_fields.text_field :siret_number %>

      <%= client_fields.label :tva_number, "Numéro de TVA" %>
      <%= client_fields.text_field :tva_number %>

      <%= client_fields.label :email, "Email" %>
      <%= client_fields.text_field :email %>

      <%= client_fields.label :phone_number, "Téléphone" %>
      <%= client_fields.text_field :phone_number %>

    <% end %>

    <button data-action="click->items#addItem">
      <p>Ajouter un article</p>
    </button>

    <% 10.times do |i| %>
      <div data-items-target="items">
        <%= form.fields_for :item, index: i do |item_fields| %>

          <%= item_fields.label :name, "Désignation" %>
          <%= item_fields.text_field :name %>

          <%= item_fields.label :description, "Description" %>
          <%= item_fields.text_field :description %>

          <%= item_fields.label :unity, "Unité" %>
          <%= item_fields.select :unity, in: Item::UNITY %>

          <%= item_fields.label :quantity, "Quantité" %>
          <%= item_fields.text_field :quantity %>

          <%= item_fields.label :unit_price, "Prix unitaire" %>
          <%= item_fields.text_field :unit_price %>

        <% end %>
      </div>
    <% end %>

    <%= form.submit "Générer la facture" %>
  <% end %>
</div>

app/views/bills/show.html.erb
<div class="container-bill">

  <h1>Facture</h1>

  <div>
    <div class="bill-informations">
      <p>Numéro de facture</p>
      <p><%= "F-2023-#{if @bill.number < 10 ? "0#{@bill.number.to_s}" : @bill.number.to_s}" %></p>
    </div>
    <div class="bill-informations">
      <p>Date d'émission</p>
      <p><%= @bill.emission_date %></p>
    </div>
    <div class="bill-informations">
      <p>Date d'échéance</p>
      <p><%= @bill.due_date %></p>
    </div>
  </div>

  <div class="bill-entities">
    <div>
      <p><strong><%= @bill.admin.name %></strong></p>
      <p><%= @bill.admin.address %></p>
      <p><%= "#{@bill.admin.post_code}, #{@bill.admin.city}" %></p>
      <p><%= @bill.admin.siret_number %></p>
      <p><%= @bill.admin.email %></p>
    </div>
    <div>
      <p><strong><%= @bill.client.name %></strong></p>
      <p><%= @bill.client.address %></p>
      <p><%= "#{@bill.client.post_code}, #{@bill.client.city}" %></p>
      <p><%= @bill.client.siret_number %></p>
    </div>
  </div>

  <div class="bill-designations">
    <div class="bill-global-row">
      <p>Items</p>
      <p>Unité</p>
      <p>Quantité</p>
      <p>Prix Unitaire</p>
      <p>Total</p>
    </div>
    <%= @bill.items.each |item| do %>
      <div class="bill-row">
        <p><%= item.name %></p>
        <p><%= item.unity %></p>
        <p><%= item.quantity %></p>
        <p><%= item.unit_price %></p>
        <p><%= item.total_price %></p>
      </div>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Développeur Web</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "favicon.png", rel: "icon", type: "image/png" %>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_about.html.erb
<div data-smartphone-target='about' data-appear-target="aboutContainer" data-scroll-target='about' class="container-basic container-padding-y">
  <div class="about-disclaimer">
    <p data-appear-target='about aboutContainerTrigger' data-category="about" class='text-grey left-hidden'>À PROPOS</p>
    <div class='disclaimer-list'>
      <h3 data-appear-target='about' class='text-white spacing-little-line hidden-bottom'>
        Passionné par les technologies du web, je suis un développeur fullstack qui aime combiner créativité et convivialité des interfaces.
      </h3>
      <div data-appear-target='about' class="disclaimer-description hidden-bottom">
        <p class='text-grey number-position'>01.</p>
        <p class='text-biggest text-white text-regular spacing-large-line'>Collaborant étroitement avec des équipes orientées vers la conception web et sites sur mesure, ma capacité à m'adapter rapidement et à travailler efficacement en équipe me permet de contribuer pleinement aux projets.</p>
      </div>
      <div data-appear-target='about' class="disclaimer-description hidden-bottom">
        <p class='text-grey number-position'>02.</p>
        <p class='text-biggest text-white text-regular spacing-large-line'>Créer des expériences web attrayantes et conviviales en adaptant mes solutions aux besoins spécifiques des clients est mon leitmotiv. Ceci ayant pour but d'offrir des expériences web de qualité.</p>
      </div>
    </div>
  </div>
  <div class="about-expertise">
    <p data-appear-target='about' class='text-grey left-hidden'>EXPERTISES</p>
    <div>
      <div class="skill-category">
        <h4 data-appear-target='about' class='text-white hidden-bottom'>Back-end</h4>
        <div class="skill-category-wrapper">
          <div data-appear-target='about' class='skill-category-row skills-hidden skills-hidden-smartphone'>
            <div class="skill-block">
              <%= image_tag 'icones_language/icone_ruby.svg', alt: 'icone RUBY' %>
              <p class='text-white'>RUBY</p>
            </div>
            <div class="skill-block">
              <%= image_tag 'icones_language/icone_rails.svg', alt: 'icone RAILS', class: 'text-icone' %>
              <p class='text-white'>RAILS</p>
            </div>
            <div class="skill-block">
              <%= image_tag 'icones_language/icone_postgresql.svg', alt: 'icone POSTGRE SQL' %>
              <p class='text-white'>POSTGRE SQL</p>
            </div>
          </div>
        </div>
      </div>
      <div class="skill-category">
        <h4 data-appear-target='about' class='text-white hidden-bottom'>Front-end</h4>
        <div class="skill-category-wrapper">
          <div data-appear-target='about' class='skill-category-row skills-hidden skills-hidden-smartphone'>
            <div class="skill-block">
              <%= image_tag 'icones_language/icone_tailwind.svg', alt: 'icone TAILWIND' %>
              <p class='text-white'>TAILWIND CSS</p>
            </div>
            <div class="skill-block">
              <%= image_tag 'icones_language/icone_stimulus.svg', alt: 'icone STIMULUS' %>
              <p class='text-white'>STIMULUS</p>
            </div>
            <div class="skill-block">
              <%= image_tag 'icones_language/icone_turbo.svg', alt: 'icone TURBO' %>
              <p class='text-white'>TURBO</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/_contact.html.erb
<div
  data-smartphone-target='contact' data-scroll-target='contact'
  data-appear-target="contactContainer" data-category="contact"
  class="container-basic container-padding-y"
>
  <div data-controller='clipboard' class="container-contact">
    <p data-appear-target='contact' class='text-grey hidden-bottom'>CONTACTEZ MOI</p>
    <a href="mailto:contact@kevintchiadeu.com" target='_blank'>
      <h1 data-appear-target='contact' data-clipboard-target='mail' class='text-white custom-h1 hidden-bottom'>contact@<br>kevintchiadeu.com</h1>
    </a>
    <div data-appear-target='contact'
        data-clipboard-target='button'
        data-action='click->clipboard#copy mouseleave->clipboard#resetText'
        class="button button-black button-copy hidden-bottom">
      <svg width="12" height="14" viewBox="0 0 12 14" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" clip-rule="evenodd" d="M2.90445 0.976074H12V10.0716H2.90445V0.976074ZM0 3.92857H2.4V10.5767H9.09593V13.0241H0.000386267V3.92857H0Z"/>
      </svg>
      <p data-clipboard-target='text' class='text-medium'>Copier</p>
    </div>
  </div>
</div>

app/views/pages/_loading_page.html.erb
<div data-loading-target='loadingPage' class="container-loading">
  <div data-loading-target='name' class="name-loading">
    <h4 class='text-white'>Kévin Tchiadeu</h4>
    <p class='text-grey'>DÉVELOPPEUR FULLSTACK</p>
  </div>
  <p data-loading-target='counter' class='counter-loading text-custom text-white'>0</p>
  <div data-loading-target='bar' class='bar-loading'></div>
</div>

app/views/pages/_navbar.html.erb
<div data-appear-target='content' class='navbar slide-in-navbar slide-in-navbar-mobile'>
  <p data-smartphone-target='navbarName' class='text-biggest'>Kévin Tchiadeu</p>
  <div class='navbar-options'>
    <div data-action='click->scroll#scrollToAbout' class='button'>
      <p class='text-large text-grey text-regular'>À propos</p>
    </div>
    <div data-action='click->scroll#scrollToProjects' class='button'>
      <p class='text-large text-grey text-regular'>Projets</p>
    </div>
    <div data-action='click->scroll#scrollToContact' class='button'>
      <p class='text-large text-grey text-regular'>Contact</p>
    </div>
  </div>
  <%= image_tag 'icones/burger.svg', class: 'icone-burger',
                data: {action: 'click->smartphone#navbarOptions', smartphone_target: 'navbarBurger'} %>
  <%= image_tag 'icones/cross.svg', class: 'icone-cross',
                data: {action: 'click->smartphone#closeOptions', smartphone_target: 'navbarCross'} %>
</div>

app/views/pages/_project.html.erb
<div data-category="project" class="project-card hidden-project" data-appear-target='project <%= trigger %>'>
  <div class="project-cover">
    <%= image_tag "projects_cover/#{cover_image}", class: 'project-image', alt: alt %>
    <div class="project-date">
      <p class="text-white text-small text-visible"><%= month.upcase %> <%= year %></p>
    </div>
    <div class="project-skills-list">
      <% skills.each do |skill| %>
        <div class="project-skill">
          <p class="text-white text-small text-visible"><%= skill.upcase %></p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="project-infos">
    <div>
      <h5><%= project_name.upcase %></h5>
      <p class='text-grey text-regular'><%= project_description %></p>
    </div>
    <%= link_to url, target: '_blank' do %>
      <div class="project-icone-plus-smartphone">
        <%= image_tag 'icones/plus.svg' %>
        <p>Découvrir</p>
      </div>
      <div class="project-icone-plus">
        <%= image_tag 'icones/plus.svg' %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/_projects.html.erb
<div
  data-smartphone-target='projects' data-scroll-target='projects'
  data-appear-target="projectContainer"
  class="container-basic container-padding-y"
>
  <div data-appear-target='project projectContainerTrigger' data-category="project" class="projects-title hidden-bottom">
    <p class='text-grey'>2023</p>
    <h2>PROJETS RÉALISÉS</h2>
  </div>
  <div class="projects-grid">
    <%=
      render partial: "project",
      locals: {
        trigger: "",
        cover_image: "breizh_secrets.jpg",
        alt: "Photo des remparts de St Malo",
        month: "mars",
        year: "2023",
        skills: ["rails", "postgre sql", "html", "css", "stimulus"],
        project_name: "breizh secrets",
        project_description: "Application de découverte de la Bretagne sous forme de jeu de piste",
        url: "https://www.breizhsecrets.eu"
      }
    %>
    <%=
      render partial: "project",
      locals: {
        trigger: "projectContainerTrigger",
        cover_image: "s&s_calendar.png",
        alt: "Aperçu landing page S&S Calendar",
        month: "septembre",
        year: "2023",
        skills: ["rails", "google calendar API", "google vision API"],
        project_name: "Snap & Sync Calendar",
        project_description: "Application de gestion de calendrier synchronisé avec Google Calendar",
        url: "https://from-pics-to-calendar.osc-fr1.scalingo.io/users/sign_in"
      }
    %>
  </div>
</div>

app/views/pages/contacter.html.erb
<div class="smartphone-container">
  <%= image_tag "iphone.png", alt: "iphone_background", class: "smartphone-image" %>
  <div class="smartphone">
    <div class="smartphone-content">
      <!-- Inset the content here to have the background as you are navigating through the smartphone -->
      <%= image_tag "avatar.png", alt: "photo kevin tchiadeu", class: "avatar" %>
      <div class="smartphone-infos">
        <h4 class="text-white">Kévin TCHIADEU</h4>
        <p class="text-grey">DÉVELOPPEUR FULLSTACK</p>
        <%= link_to add_contact_path do %>
          <div class="button-smartphone">
            <p class="text-medium">Ajouter à mes contacts</p>
            <i class="fa-regular fa-address-book"></i>
          </div>
        <% end %>
      </div>
      <div class="break-bar"></div>
      <div class="social-media">
        <a href="https://www.kevintchiadeu.com" target="_blank">
          <div class="social-media-block">
            <%= image_tag "icones_social_media/website.png", alt: "site", class: "social-media-icon" %>
            <p class="text-white text-large">Site</p>
          </div>
        </a>
        <a href="https://www.calendly.com/kevintchiadeu" target="_blank">
          <div class="social-media-block">
            <%= image_tag "icones_social_media/calendly.png", alt: "calendly", class: "social-media-icon" %>
            <p class="text-white text-large">Calendly</p>
          </div>
        </a>
        <%= link_to "https://www.linkedin.com/in/kevin-tchiadeu/", target: "_blank" do %>
          <div class="social-media-block">
            <%= image_tag "icones_social_media/linkedin.png", alt: "linkedin", class: "social-media-icon" %>
            <p class="text-white text-large">Linkedin</p>
          </div>
        <% end %>
        <%= link_to "https://github.com/tchiadeu", target: "_blank" do %>
          <div class="social-media-block">
            <%= image_tag "icones_social_media/github.png", alt: "github", class: "social-media-icon" %>
            <p class="text-white text-large">Github</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<%= link_to "Nouvelle Facture", new_bill_path %>

app/views/pages/home.html.erb
<div data-controller='loading'>
  <%= render 'loading_page' %>
  <div data-controller='scroll appear smartphone' data-loading-target='landing' class='landing'>
    <div data-smartphone-target='background' data-category="content" data-appear-target="contentContainer" class="container-basic container-full-height">
      <%= render 'navbar' %>
      <div data-smartphone-target='smartphoneOptions' class='smartphone-options'>
        <div data-action='click->smartphone#scrollTo' data-category="about" class='button'>
          <p class='text-large text-grey text-regular'>À propos</p>
        </div>
        <div data-action='click->smartphone#scrollTo' data-category="projects" class='button'>
          <p class='text-large text-grey text-regular'>Projets</p>
        </div>
        <div data-action='click->smartphone#scrollTo' data-category="contact" class='button'>
          <p class='text-large text-grey text-regular'>Contact</p>
        </div>
      </div>
      <div data-smartphone-target='content' class="container-content">
        <h1 class='slide-in-title slide-in-title-mobile'>
          développeur <br>fullstack
        </h1>
        <div class='content-infos'>
          <div class='content-description'>
            <div class='content-description-principal slide-in-description slide-in-description-mobile'>
              <p class='text-responsive text-regular text-grey spacing-large-line'>
                👋 Bonjour,
                <br>Je suis Kévin Tchiadeu, <%= @age %> ans, développeur fullstack freelance basé à Rennes.
                Je vous propose mes services dans la conception de vos plateformes digitales.
              </p>
              <a href="mailto:contact@kevintchiadeu.com">
                <div class="button button-black button-home slide-in-button slide-in-button-mobile">
                  <%= image_tag 'icones/mail.svg' %>
                  <p class='text-medium'>Contactez-moi</p>
                </div>
              </a>
            </div>
            <div data-action='click->scroll#scrollToAbout' class="button">
              <%= image_tag 'icones/arrow.svg', class: 'arrow-down slide-in-arrow slide-in-arrow-mobile' %>
            </div>
          </div>
          <div class="content-cover-position">
            <div class="content-cover">
              <div class="content-cover-filter cover-reveal cover-reveal-mobile"></div>
              <%= image_tag 'developpeur_web.jpg', class: 'content-image image-reveal image-reveal-mobile', alt: 'developpeur web' %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render 'about' %>
    <%= render 'projects' %>
    <%= render 'contact' %>
  </div>
</div>

app/views/pages/navbar.html.erb
<div class='navbar'>
  <p class='navbar-name'>Kévin Tchiadeu</p>
  <div class='navbar-options'>
    <p>À propos</p>
    <p>Projets</p>
    <p>Contact</p>
  </div>
</div>